name: vaden
description: Dart backend project create by Flutterando community. Using and action!
version: 0.0.1
repository: https://github.com/Flutterando/vaden

environment:
  sdk: ^3.6.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  auto_injector: ^2.0.5
  lucid_validation: ^1.2.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
