name: vaden
description: Dart backend project create by Flutterando community. Using and action!
version: 0.0.1
repository: https://github.com/Flutterando/vaden

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
