name: vaden_class_scanner
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  source_gen: ^2.0.0
  analyzer: ^7.2.0
  build: ^2.4.2
  vaden: 
  glob: ^2.1.3
  path: ^1.9.1
  dart_style: ^3.0.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.14
  lints: ^5.0.0
  test: ^1.24.0
